// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLF1Clnv5JJUpcmY-naXmn6eO0eaLpg0',
    appId: '1:835510226203:web:901e2d5e387bdf637a17be',
    messagingSenderId: '835510226203',
    projectId: 'warkopibadah-f91c9',
    authDomain: 'warkopibadah-f91c9.firebaseapp.com',
    storageBucket: 'warkopibadah-f91c9.appspot.com',
    measurementId: 'G-7FWRV5V0VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADNNacf03vLFkgPiKaMbbajI9RLG2dwgM',
    appId: '1:835510226203:android:eb3aec5b618652b17a17be',
    messagingSenderId: '835510226203',
    projectId: 'warkopibadah-f91c9',
    storageBucket: 'warkopibadah-f91c9.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPLF1Clnv5JJUpcmY-naXmn6eO0eaLpg0',
    appId: '1:835510226203:web:29c5d985a5f335057a17be',
    messagingSenderId: '835510226203',
    projectId: 'warkopibadah-f91c9',
    authDomain: 'warkopibadah-f91c9.firebaseapp.com',
    storageBucket: 'warkopibadah-f91c9.appspot.com',
    measurementId: 'G-S8PL1L13FM',
  );
}
